# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hhrawInfo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='日期')),
                ('runoff', models.FloatField(verbose_name='径流量')),
                ('precipitation', models.FloatField(verbose_name='降雨量')),
                ('evaporation', models.FloatField(verbose_name='蒸发量')),
                ('temperature', models.FloatField(verbose_name='温度')),
            ],
        ),
    ]
